### ISSUE TITLE
ThemeSideBar: UI improvements

### ISSUE THREAD

**Issue by Zuurkern** [react-theming/storybook-addon-material-ui#71]
I want to improve the UI of the theming sidebar but I am a bit puzzled about how to go about this.

What's the best way to see the changes I am making while I'm developing? Or @UsulPro what did you use to create it?

Also related to [Material UI next support](https://github.com/react-theming/storybook-addon-material-ui/issues/62) as I want to use their components to create a better UI.

**Comment by Zuurkern** [comment]
I also noticed it's built with inline styles at the moment. Do you think we could leverage JSS as well for these improvements?

**Comment by UsulPro** [comment]
HI @Zuurkern 
I'm really sorry for such late answer. But you raised pretty discussable questions and I couldn't respond without deeper research about how `storybook-addon-material-ui` should look and work in the future. 
Now I can explain that I'm sure `theme sidebar` should be removed since it's legacy solution from Storybook 1 version. Instead, I want to keep all themes manipulation in the addon panel, possible a few panels after new layout will be implemented.
I suppose it'll be realized in parallel with Material-UI v1 [support](https://github.com/react-theming/storybook-addon-material-ui/tree/next). 
JSS based styles are one of the features I'd like to implement first as well.

closing this since we have  #62  to track v1 version
